import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import axios from "axios";

export default function Home() {
  const [dataRequest, setDataRequest] = useState({
    email: "",
    password: "",
  });

  const handleChange = (key, value) => {
    setDataRequest((prev) => {
      return {
        ...prev,
        [key]: value,
      };
    });
  };

  const login = async (e) => {
    e.preventDefault();
    console.log(dataRequest)
    try {
      const result = await axios({
        url: "../api/login",
        method: "POST",
        data: dataRequest,
      });
      console.log(result);
    } catch (error) {
      alert(error);
    }
  };

  return (
    <>
      <Head>
        <title>Event Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form
          onSubmit={login}
          style={{
            display: "flex",
            flexDirection: "column",
            padding: "30px",
            border: "1px solid white",
            borderRadius: "8px",
            width: "300px",
          }}
        >
          <label htmlFor="email">Email</label>
          <input
            id="email"
            type="email"
            onChange={(e) => handleChange("email", e.target.value)}
          />
          <label htmlFor="password">Password</label>
          <input
            id="password"
            type="password"
            onChange={(e) => handleChange("password", e.target.value)}
          />
          <button>Sign In</button>
        </form>
      </main>
    </>
  );
}
